sudo: required

services:
    - docker

before-install:
    - docker build -t yogeshatos/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true yogeshatos/docker-react npm run test

deploy:
    provider: elasticbeanstalk
    region: "eu-central-1"
    app: "docker-react"
    env: "DockerReact-env"
    bucket_name: "elasticbeanstalk-eu-central-1-643768221368"
    bucket_path: "docker_react"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    